import { company } from "@/config/company";
import { footerNavigation } from "@/config/footer";
import { primaryNavigation } from "@/config/navigation";
import { siteConfig } from "@/config/site";
import type { PublicSiteSettings } from "@/types/settings";

export const fallbackSiteSettings: PublicSiteSettings = {
  id: "00000000-0000-4000-8000-000000000001",
  site_name: company.name,
  tagline: company.tagline,
  site_url: siteConfig.url,
  default_language: "en",
  timezone: "UTC",
  logo_media_id: null,
  favicon_media_id: null,
  open_graph_media_id: null,
  default_meta_title: siteConfig.name,
  default_meta_description: siteConfig.description,
  default_keywords: siteConfig.keywords,
  robots: "index,follow",
  canonical_base_url: siteConfig.url,
  contact_email: company.email,
  contact_phone: null,
  whatsapp: null,
  address: company.location,
  google_maps_url: null,
  facebook_url: null,
  instagram_url: null,
  linkedin_url: null,
  github_url: null,
  x_url: null,
  youtube_url: null,
  header_navigation: primaryNavigation.map(({ label, href }) => ({
    label,
    href,
  })),
  footer_navigation: footerNavigation.map(({ title, links }) => ({
    title,
    links: links.map(({ label, href }) => ({ label, href })),
  })),
  footer_copyright: "All rights reserved.",
  working_hours: null,
  emergency_contact: null,
  business_registration_number: null,
  google_analytics_id: null,
  google_search_console_verification: null,
  google_tag_manager_id: null,
  microsoft_clarity_id: null,
  plausible_domain: null,
  vercel_analytics_enabled: false,
  enable_blog: true,
  enable_testimonials: true,
  enable_contact_form: true,
  enable_newsletter: false,
  enable_ai_features: true,
  maintenance_mode: false,
  maintenance_message:
    "The website is temporarily unavailable while maintenance is completed.",
  status: "published",
  logo: null,
  favicon: null,
  openGraphImage: null,
  homepage_heading: "Build Smarter. Automate Faster. Scale Without Limits.",
  homepage_subheading:
    "Ayeb Solutions helps businesses grow through premium websites, AI automation, custom software, and intelligent digital solutions that save time and increase revenue.",
  homepage_badge: "AI Automation • Web Development • SaaS Solutions",
  homepage_primary_cta_label: "Book Free Consultation",
  homepage_primary_cta_href: "/contact",
  homepage_secondary_cta_label: "View Our Work",
  homepage_secondary_cta_href: "/portfolio",
  homepage_hero_media_id: null,
  homepage_background_media_id: null,
  homepage_statistics: [],
  homepage_trust_indicators: [
    "Fast Delivery",
    "AI Powered",
    "Secure Development",
    "Long-Term Support",
  ],
  homepage_services_limit: 6,
  homepage_portfolio_limit: 6,
  homepage_blog_limit: 3,
  homepage_testimonials_limit: 6,
  homepage_cta_heading:
    "Ready to Turn Your Ideas Into Powerful Digital Solutions?",
  homepage_cta_description:
    "Whether you're launching a startup, modernizing an existing business, or exploring AI automation, we're here to help plan and build the right solution.",
  homepage_cta_primary_label: "Book Free Consultation",
  homepage_cta_primary_href: "/contact",
  homepage_cta_secondary_label: "View Services",
  homepage_cta_secondary_href: "/services",
  homepageHeroMedia: null,
  homepageBackgroundMedia: null,
};
export async function getPublicSiteSettings(): Promise<PublicSiteSettings> {
  return fallbackSiteSettings;
}
