import type { ServiceRow } from "@/types/database";

const audit = {
  created_at: "2026-01-01T00:00:00.000Z",
  created_by: null,
  updated_at: "2026-01-01T00:00:00.000Z",
  updated_by: null,
} as const;

export const marketingServices: readonly ServiceRow[] = [
  {
    ...audit,
    id: "static-web-development",
    title: "Web Development",
    slug: "web-development",
    summary:
      "Fast, accessible websites and web applications built around clear business goals.",
    description:
      "Custom websites, applications, portals, and digital experiences.",
    category_id: null,
    icon: "code2",
    keywords: ["web development", "Next.js", "React"],
    features: [
      "Responsive design",
      "SEO foundations",
      "Accessible interfaces",
      "Performance-focused delivery",
    ],
    technologies: ["Next.js", "React", "TypeScript", "PostgreSQL"],
    status: "published",
    is_featured: true,
    sort_order: 10,
    meta_title: null,
    meta_description: null,
    subtitle: null,
    benefits: [],
    process: [],
    deliverables: [],
    faq: [],
  },
  {
    ...audit,
    id: "static-ai-automation",
    title: "AI Automation",
    slug: "ai-automation",
    summary:
      "Reviewable AI-assisted workflows that connect tools, reduce repetition, and support teams.",
    description:
      "AI agents, workflow automation, CRM automation, and human-in-the-loop systems.",
    category_id: null,
    icon: "bot",
    keywords: ["AI automation", "workflows", "OpenAI"],
    features: [
      "Workflow mapping",
      "Human approval",
      "System integrations",
      "Exception handling",
    ],
    technologies: ["OpenAI", "Node.js", "PostgreSQL", "Webhooks"],
    status: "published",
    is_featured: true,
    sort_order: 20,
    meta_title: null,
    meta_description: null,
    subtitle: null,
    benefits: [],
    process: [],
    deliverables: [],
    faq: [],
  },
  {
    ...audit,
    id: "static-saas-development",
    title: "SaaS Development",
    slug: "custom-saas",
    summary:
      "Purpose-built SaaS products, dashboards, portals, and internal platforms.",
    description:
      "Scalable product foundations with roles, reporting, billing, and integrations.",
    category_id: null,
    icon: "layers3",
    keywords: ["SaaS", "platform", "dashboard"],
    features: [
      "Multi-tenant architecture",
      "Role management",
      "Dashboards",
      "Subscription workflows",
    ],
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Docker"],
    status: "published",
    is_featured: false,
    sort_order: 30,
    meta_title: null,
    meta_description: null,
    subtitle: null,
    benefits: [],
    process: [],
    deliverables: [],
    faq: [],
  },
  {
    ...audit,
    id: "static-ui-ux-design",
    title: "UI/UX Design",
    slug: "ui-ux-design",
    summary:
      "Clear, accessible interfaces shaped through research, structure, and reusable systems.",
    description:
      "Research, user flows, wireframes, prototypes, and scalable design systems.",
    category_id: null,
    icon: "palette",
    keywords: ["UI", "UX", "design systems"],
    features: [
      "User flows",
      "Wireframes",
      "Interface design",
      "Interactive prototypes",
    ],
    technologies: ["Figma", "FigJam", "Storybook", "Framer Motion"],
    status: "published",
    is_featured: false,
    sort_order: 40,
    meta_title: null,
    meta_description: null,
    subtitle: null,
    benefits: [],
    process: [],
    deliverables: [],
    faq: [],
  },
  {
    ...audit,
    id: "static-ecommerce",
    title: "E-commerce",
    slug: "ecommerce",
    summary:
      "Commerce experiences connecting catalogues, payments, inventory, and operations.",
    description:
      "Custom storefronts and integrations designed around a maintainable sales workflow.",
    category_id: null,
    icon: "braces",
    keywords: ["e-commerce", "payments", "inventory"],
    features: [
      "Product catalogues",
      "Payment integration",
      "Inventory workflows",
      "Order management",
    ],
    technologies: ["Next.js", "Stripe", "PostgreSQL", "Cloudinary"],
    status: "published",
    is_featured: false,
    sort_order: 50,
    meta_title: null,
    meta_description: null,
    subtitle: null,
    benefits: [],
    process: [],
    deliverables: [],
    faq: [],
  },
  {
    ...audit,
    id: "static-custom-software",
    title: "Custom Software",
    slug: "custom-software",
    summary:
      "Internal systems, integrations, and operational tools tailored to real workflows.",
    description:
      "Maintainable software designed around business rules, users, and existing systems.",
    category_id: null,
    icon: "cog",
    keywords: ["custom software", "integrations", "business systems"],
    features: [
      "Business workflows",
      "API integrations",
      "Admin tools",
      "Long-term maintainability",
    ],
    technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
    status: "published",
    is_featured: false,
    sort_order: 60,
    meta_title: null,
    meta_description: null,
    subtitle: null,
    benefits: [],
    process: [],
    deliverables: [],
    faq: [],
  },
];
